export const data = [
{
	question: 'Which service in a PKI will vouch for the identity of an individual or company?',
	option1: ' KDC ',
	option2: ' CR ',
	option3: ' CBC ',
	option4: ' CA',
	ans: 4,
},
{
	question: 'Identify the web application attack where the attackers exploit vulnerabilities in dynamically generated web pages to inject client-side script into web pages viewed by other users.',
	option1: ' LDAP Injection attack ',
	option2: ' Cross-Site Scripting (XSS) ',
	option3: ' SQL injection attack ',
	option4: ' Cross-Site Request Forgery (CSRF)',
	ans: 2,
},
{
	question: 'User A is writing a sensitive email message to user B outside the local network. User A has chosen to use PKI to secure his message and ensure only user B can read the sensitive email. At what layer of the OSI layer does the encryption and decryption of the message take place?',
	option1: ' Application ',
	option2: ' Transport ',
	option3: ' Session ',
	option4: ' Presentation',
	ans: 4,
},
{
	question: 'If you want to only scan fewer ports than the default scan using Nmap tool, which option would you use?',
	option1: ' -r ',
	option2: ' -F ',
	option3: ' -P ',
	option4: ' -sP',
	ans: 2,
},
{
	question: 'Which of the following is the structure designed to verify and authenticate the identity of individuals within the enterprise taking part in a data exchange?',
	option1: ' SOA ',
	option2: ' biometrics ',
	option3: ' single sign on ',
	option4: ' PKI',
	ans: 4,
},
{
	question: "You are tasked to perform a penetration test. While you are performing information gathering, you find an employee list in Google. You find the receptionist's email, and you send her an email changing the source email to her boss's email (boss@company). In this email, you ask for a pdf with information. She reads your email and sends back a pdf with links. You exchange the pdf links with your malicious links (these links contain malware) and send back the modified pdf, saying that the links don't work. She reads your email, opens the links, and her machine gets infected. You now have access to the company network. What testing method did you use?",
	option1: ' Social engineering ',
	option2: ' Piggybacking ',
	option3: ' Tailgating ',
	option4: ' Eavesdropping',
	ans: 1,
},
{
	question: 'If a tester is attempting to ping a target that exists but receives no response or a response that states the destination is unreachable, ICMP may be disabled and the network may be using TCP. Which other option could the tester use to get a response from a host using TCP?',
	option1: ' Traceroute ',
	option2: ' Hping ',
	option3: ' TCP ping ',
	option4: ' Broadcast ping',
	ans: 2,
},
{
	question: 'Which is the first step followed by Vulnerability Scanners for scanning a network?',
	option1: ' OS Detection ',
	option2: ' Firewall detection ',
	option3: ' TCP/UDP Port scanning ',
	option4: ' Checking if the remote host is alive',
	ans: 4,
},
{
	question: 'Which of the following programs is usually targeted at Microsoft Office products?',
	option1: ' Polymorphic virus ',
	option2: ' Multipart virus ',
	option3: ' Macro virus ',
	option4: ' Stealth virus',
	ans: 3,
},
{
	question: "In an internal security audit, the white hat hacker gains control over a user account and attempts to acquire access to another account's confidential files and information. How can he achieve this?",
	option1: ' Privilege Escalation ',
	option2: ' Shoulder-Surfing ',
	option3: ' Hacking Active Directory ',
	option4: ' Port Scanning',
	ans: 1,
},
{
	question: 'Identify the UDP port that Network Time Protocol (NTP) uses as its primary means of communication?',
	option1: ' 113 ',
	option2: '69 ',
	option3: '123 ',
	option4: '161',
	ans: 3,
},

{
	question: 'Which of the following tools performs comprehensive tests against web servers, including dangerous files and CGIs?',
	option1: ' Nikto ',
	option2: ' John the Ripper ',
	option3: ' Dsniff ',
	option4: ' Snort',
	ans: 1,
},
{
	question: 'Which of the following is an extremely common IDS evasion technique in the web world?',
	option1: ' Spyware ',
	option2: ' Subnetting ',
	option3: ' Unicode Characters ',
	option4: ' Port Knocking',
	ans: 3,
},
{
	question: 'John the Ripper is a technical assessment tool used to test the weakness of which of the following?',
	option1: 'Passwords ',
	option2: 'File permissions ',
	option3: 'Firewall rulesets ',
	option4: 'Usernames',
	ans: 1,
},
{
	question: "Some clients of TPNQM SA were redirected to a malicious site when they tried to access the TPNQM main site. Bob, a system administrator at TPNQM SA, found that they were victims of DNS Cache Poisoning.What should Bob recommend to deal with such a threat?",
	option1: " The use of security agents in clients' computers ",
	option2: ' The use of DNSSEC ',
	option3: 'The use of double-factor authentication ',
	option4: 'Client awareness',
	ans: 2,
},
{
	question: 'During a black-box pen test you attempt to pass IRC traffic over port 80/TCP from a compromised web enabled host. The traffic gets blocked; however, outboundHTTP traffic is unimpeded. What type of firewall is inspecting outbound traffic?',
	option1: 'Circuit ',
	option2: 'Stateful ',
	option3: 'Application Most Voted ',
	option4: ' Packet Filtering',
	ans: 2,
},
{
	question: 'By using a smart card and pin, you are using a two-factor authentication that satisfies',
	option1: ' Something you are and something you remember ',
	option2: ' Something you have and something you know ',
	option3: ' Something you know and something you are ',
	option4: ' Something you have and something you are',
	ans: 2,
},
{
	question: '`........is an attack type for a rogue Wi-Fi access point that appears to be a legitimate one offered on the premises, but actually has been set up to eavesdrop on wireless communications. It is the wireless version of the phishing scam. An attacker fools wireless users into connecting a laptop or mobile phone to a tainted hotspot by posing as a legitimate provider. This type of attack may be used to steal the passwords of unsuspecting users by either snooping the communication link or by phishing, which involves setting up a fraudulent web site and luring people there.`Fill in the blank with appropriate choice.',
	option1: ' Evil Twin Attack ',
	option2: ' Sinkhole Attack ',
	option3: ' Collision Attack ',
	option4: ' Signal Jamming Attack',
	ans: 1,
},
{
	question: 'A regional bank hires your company to perform a security assessment on their network after a recent data breach. The attacker was able to steal financial data from the bank by compromising only a single server. Based on this information, what should be one of your key recommendations to the bank?',
	option1: ' Place a front-end web server in a demilitarized zone that only handles external web traffic ',
	option2: ' Require all employees to change their anti-virus program with a new one ',
	option3: ' Move the financial data to another server on the same IP subnet ',
	option4: ' Issue new certificates to the web servers from the root certificate authority',
	ans: 1,
},
{
	question: 'What term describes the amount of risk that remains after the vulnerabilities are classified and the countermeasures have been deployed?',
	option1: ' Residual risk ',
	option2: ' Impact risk ',
	option3: ' Deferred risk ',
	option4: ' Inherent risk',
	ans: 1,
},
{
	question: 'Which of the following is the best countermeasure to encrypting ransomwares?',
	option1: ' Use multiple antivirus softwares ',
	option2: ' Pay a ransom ',
	option3: ' Keep some generation of off-line backup ',
	option4: ' Analyze the ransomware to get decryption key of encrypted data',
	ans: 3,
},
{
	question: 'Session splicing is an IDS evasion technique in which an attacker delivers data in multiple, small sized packets to the target computer, making it very difficult for anIDS to detect the attack signatures. Which tool can be used to perform session splicing attacks?',
	option1: ' tcpsplice ',
	option2: ' Burp ',
	option3: ' Hydra ',
	option4: ' Whisker',
	ans: 4,
},
{
	question: 'Which of the following is the BEST way to defend against network sniffing?',
	option1: ' Using encryption protocols to secure network communications Most Voted ',
	option2: ' Register all machines MAC Address in a Centralized Database ',
	option3: ' Use Static IP Address ',
	option4: ' Restrict Physical Access to Server Rooms hosting Critical Servers',
	ans: 1,
},
{
	question: 'Which of the following is the least-likely physical characteristic to be used in biometric control that supports a large company?',
	option1: ' Iris patterns ',
	option2: ' Voice ',
	option3: ' Height and Weight ',
	option4: ' Fingerprints',
	ans: 3,
},
{
	question: 'Although FTP traffic is not encrypted by default, which layer 3 protocol would allow for end-to-end encryption of the connection?',
	option1: ' SFTP ',
	option2: ' Ipsec ',
	option3: ' SSL ',
	option4: ' FTPS',
	ans: 2,
},
{
	question: 'You are the Network Admin, and you get a complaint that some of the websites are no longer accessible. You try to ping the servers and find them to be reachable. Then you type the IP address and then you try on the browser, and find it to be accessible. But they are not accessible when you try using the URL.What may be the problem?',
	option1: ' Traffic is Blocked on UDP Port 53 ',
	option2: ' Traffic is Blocked on TCP Port 80 ',
	option3: ' Traffic is Blocked on TCP Port 54 ',
	option4: ' Traffic is Blocked on UDP Port 80',
	ans: 1,
},
{
	question: 'Which of the following tools is used to detect wireless LANs using the 802.11a/b/g/n WLAN standards on a Linux platform?',
	option1: 'Kismet ',
	option2: 'Abel ',
	option3: 'Netstumbler ',
	option4: 'Nessus',
	ans: 1,
},
{
	question: "You are working as a Security Analyst in a company XYZ that owns the whole subnet range of 23.0.0.0/8 and 192.168.0.0/8.While monitoring the data, you find a high number of outbound connections. You see that IP's owned by XYZ (Internal) and private IP's are communicating to aSingle Public IP. Therefore, the Internal IP's are sending data to the Public IP.After further analysis, you find out that this Public IP is a blacklisted IP, and the internal communicating devices are compromised.What kind of attack does the above scenario depict?",
	option1: ' Botnet Attack ',
	option2: ' Spear Phishing Attack ',
	option3: ' Advanced Persistent Threats ',
	option4: ' Rootkit Attack',
	ans: 1,
},
{
	question: "Scenario:1. Victim opens the attacker's web site.2. Attacker sets up a web site which contains interesting and attractive content like `˜Do you want to make $1000 in a day?'.3. Victim clicks to the interesting and attractive content URL.4. Attacker creates a transparent `˜iframe' in front of the URL which the victim attempts to click, so the victim thinks that he/she clicks on the `˜Do you want to make$1000 in a day?' URL but actually he/she clicks on the content or URL that exists in the transparent 'iframe' which is setup by the attacker.What is the name of the attack which is mentioned in the scenario?",
	option1: ' Session Fixation ',
	option2: ' HTML Injection ',
	option3: ' HTTP Parameter Pollution ',
	option4: ' Clickjacking Attack',
	ans: 4,
},
{
	question: "A network administrator discovers several unknown files in the root directory of his Linux FTP server. One of the files is a tarball, two are shell script files, and the third is a binary file is named `nc.` The FTP server's access logs show that the anonymous user account logged in to the server, uploaded the files, and extracted the contents of the tarball and ran the script using a function provided by the FTP server's software. The ps command shows that the nc file is running as process, and the netstat command shows the nc process is listening on a network port.What kind of vulnerability must be present to make this remote attack possible?",
	option1: ' File system permissions ',
	option2: ' Privilege escalation ',
	option3: ' Directory traversal ',
	option4: ' Brute force login',
	ans: 1,
},
{
	question: 'Which of the following programming languages is most susceptible to buffer overflow attacks, due to its lack of a built-in bounds checking mechanism?Code:#include &lt;string.h> int main(){ char buffer[8];strcpy(buffer, ``11111111111111111111111111111``);} Output: Segmentation fault',
	option1: ' C# ',
	option2: ' Python ',
	option3: ' Java ',
	option4: ' C++',
	ans: 4,
},
{
	question: 'Internet Protocol Security IPsec is actually a suite pf protocols. Each protocol within the suite provides different functionality. Collective IPsec does everything except.',
	option1: ' Protect the payload and the headers ',
	option2: ' Encrypt ',
	option3: ' Work at the Data Link Layer ',
	option4: ' Authenticate',
	ans: 4,
},
{
	question: 'An attacker attaches a rogue router in a network. He wants to redirect traffic to a LAN attached to his router as part of a man-in-the-middle attack. What measure on behalf of the legitimate admin can mitigate this attack?',
	option1: 'Make sure that legitimate network routers are configured to run routing protocols with authenticatio',
	option2: ' ',
	option3: ' Disable all routing protocols and only use static routes ',
	option4: ' Only using OSPFv3 will mitigate this risk',
	ans: 1,
},
{
	question: 'Which method of password cracking takes the most time and effort?',
	option1: ' Dictionary attack ',
	option2: ' Shoulder surfing ',
	option3: ' Rainbow tables ',
	option4: ' Brute force',
	ans: 4,
},
{
	question: 'An attacker is trying to redirect the traffic of a small office. That office is using their own mail server, DNS server and NTP server because of the importance of their job. The attacker gain access to the DNS server and redirect the direction www.google.com to his own IP address. Now when the employees of the office want to go to Google they are being redirected to the attacker machine. What is the name of this kind of attack?',
	option1: ' MAC Flooding ',
	option2: ' Smurf Attack ',
	option3: ' DNS spoofing ',
	option4: ' ARP Poisoning',
	ans: 3,
},
{
	question: 'When purchasing a biometric system, one of the considerations that should be reviewed is the processing speed. Which of the following best describes what it is meant by processing?',
	option1: ' The amount of time and resources that are necessary to maintain a biometric system ',
	option2: ' How long it takes to setup individual user accounts ',
	option3: ' The amount of time it takes to be either accepted or rejected from when an individual provides identification and authentication information ',
	option4: ' The amount of time it takes to convert biometric data into a template on a smart card',
	ans: 3,
},
{
	question: 'You are attempting to run an Nmap port scan on a web server. Which of the following commands would result in a scan of common ports with the least amount of noise in order to evade IDS?',
	option1: 'nmap -A - Pn ',
	option2: 'nmap -sP -p-65535 -T5 ',
	option3: 'nmap -sT -O -T0 ',
	option4: 'nmap -A --host-timeout 99 -T1',
	ans: 3,
},
{
	question: 'What does the "-oX" flag do in an Nmap scan?',
	option1: ' Perform an eXpress scan ',
	option2: ' Output the results in truncated format to the screen ',
	option3: ' Output the results in XML format to a file ',
	option4: ' Perform an Xmas scan',
	ans: 3,
},
{
	question: 'Which Intrusion Detection System is best applicable for large environments where critical assets on the network need extra scrutiny and is ideal for observing sensitive network segments?',
	option1: ' Honeypots ',
	option2: ' Firewalls ',
	option3: ' Network-based intrusion detection system (NIDS) ',
	option4: ' Host-based intrusion detection system (HIDS)',
	ans: 3,
},
{
	question: 'The collection of potentially actionable, overt, and publicly available information is known as',
	option1: ' Open-source intelligence ',
	option2: ' Real intelligence ',
	option3: ' Social intelligence ',
	option4: ' Human intelligence',
	ans: 1,
},{
	question: 'The change of a hard drive failure is once every three years. The cost to buy a new hard drive is $300. It will require 10 hours to restore the OS and software to the new hard disk. It will require a further 4 hours to restore the database from the last backup to the new hard disk. The recovery person earns $10/hour.Calculate the SLE, ARO, and ALE. Assume the EF = 1(100%). What is the closest approximate cost of this replacement and recovery operation per year?',
	option1: ' $1320 ',
	option2: ' $440 ',
	option3: ' $100 ',
	option4: ' $146',
	ans: 4,
},
{
	question: 'What is the known plaintext attack used against DES which gives the result that encrypting plaintext with one DES key followed by encrypting it with a second DES key is no more secure than using a single key?',
	option1: ' Man-in-the-middle attack ',
	option2: ' Meet-in-the-middle attack ',
	option3: ' Replay attack ',
	option4: ' Traffic analysis attack',
	ans: 2,
},
{
	question: "Steve, a scientist who works in a governmental security agency, developed a technological solution to identify people based on walking patterns and implemented this approach to a physical control access.A camera captures people walking and identifies the individuals using Steve's approach.After that, people must approximate their RFID badges. Both the identifications are required to open the door.In this case, we can say:",
	option1: ' Although the approach has two phases, it actually implements just one authentication factor ',
	option2: ' The solution implements the two authentication factors: physical object and physical characteristic ',
	option3: ' The solution will have a high level of false positives ',
	option4: ' Biological motion cannot be used to identify people',
	ans: 2,
},
{
	question: 'What is the minimum number of network connections in a multihomed firewall?',
	option1: '3 ',
	option2: '5 ',
	option3: '4 ',
	option4: '2',
	ans: 1,
},
{
	question: 'Suppose your company has just passed a security risk assessment exercise. The results display that the risk of the breach in the main company application is50%. Security staff has taken some measures and implemented the necessary controls. After that, another security risk assessment was performed showing that risk has decreased to 10%. The risk threshold for the application is 20%. Which of the following risk decisions will be the best for the project in terms of its successful continuation with the most business profit?',
	option1: ' Accept the risk ',
	option2: ' Introduce more controls to bring risk to 0% ',
	option3: ' Mitigate the risk ',
	option4: ' Avoid the risk',
	ans: 1,
},
{
	question: 'An attacker, using a rogue wireless AP, performed an MITM attack and injected an HTML code to embed a malicious applet in all HTTP connections.When users accessed any page, the applet ran and exploited many machines.Which one of the following tools the hacker probably used to inject HTML code?',
	option1: ' Wireshark ',
	option2: ' Ettercap ',
	option3: ' Aircrack-ng ',
	option4: ' Tcpdump',
	ans: 2,
},
{
	question: 'Which mode of IPSec should you use to assure security and confidentiality of data within the same LAN?',
	option1: 'ESP transport mode ',
	option2: ' ESP confidential ',
	option3: 'AH permiscuous ',
	option4: 'AH Tunnel mode',
	ans: 1,
},
{
	question: 'Hackers often raise the trust level of a phishing message by modeling the email to look similar to the internal email used by the target company. This includes using logos, formatting, and names of the target company. The phishing message will often use the name of the company CEO, President, or Managers. The time a hacker spends performing research to locate this information about a company is known as?',
	option1: 'Exploration ',
	option2: 'Investigation ',
	option3: 'Reconnaissance ',
	option4: ' Enumeration',
	ans: 3,
},
{
	question: 'Which of the following viruses tries to hide from anti-virus programs by actively altering and corrupting the chosen service call interruptions when they are being run?',
	option1: ' Macro virus ',
	option2: ' Stealth/Tunneling virus ',
	option3: ' Cavity virus ',
	option4: ' Polymorphic virus',
	ans: 2,
},{
	question: "When analyzing the IDS logs, the system administrator noticed an alert was logged when the external router was accessed from the administrator's Computer to update the router configuration. What type of an alert is this?",
	option1: ' False negative ',
	option2: ' True negative ',
	option3: ' True positive ',
	option4: ' False positive',
	ans: 4,
},
{
	question: 'A large company intends to use Blackberry for corporate mobile phones and a security analyst is assigned to evaluate the possible threats. The analyst will use the Blackjacking attack method to demonstrate how an attacker could circumvent perimeter defenses and gain access to the Prometric Online Testing `" Reports https://ibt1.prometric.com/users/custom/report_queue/rq_str... corporate network. What tool should the analyst use to perform a Blackjacking attack?',
	option1: 'Paros Proxy ',
	option2: 'BBProxy ',
	option3: 'Blooover ',
	option4: 'BBCrack',
	ans: 2,
},
{
	question: 'When you are getting information about a web server, it is very important to know the HTTP Methods (GET, POST, HEAD, PUT, DELETE, TRACE) that are available because there are two critical methods (PUT and DELETE). PUT can upload a file to the server and DELETE can delete a file from the server. You can detect all these methods (GET, POST, HEAD, PUT, DELETE, TRACE) using NMAP script engine. What Nmap script will help you with this task?',
	option1: ' http-methods ',
	option2: ' http enum ',
	option3: ' http-headers ',
	option4: ' http-git',
	ans: 1,
},
{
	question: 'Todd has been asked by the security officer to purchase a counter-based authentication system. Which of the following best describes this type of system?',
	option1: ' A biometric system that bases authentication decisions on behavioral attribute',
	option2: ' ',
	option3: ' A biometric system that bases authentication decisions on physical attribute',
	option4: ' C',
	ans: 3,
},
{
	question: 'Which of the following is a low-tech way of gaining unauthorized access to systems?',
	option1: ' Social Engineering ',
	option2: ' Eavesdropping ',
	option3: ' Scanning ',
	option4: ' Sniffing',
	ans: 1,
},
{
	question: 'Which system consists of a publicly available set of databases that contain domain name registration contact information?',
	option1: ' WHOIS ',
	option2: ' CAPTCHA ',
	option3: ' IANA ',
	option4: ' IETF',
	ans: 1,
},{
	question: "env x='(){ :;};echo exploit' bash `"c `˜cat/etc/passwd'What is the Shellshock bash vulnerability attempting to do on a vulnerable Linux host?",
	option1: ' Removes the passwd file ',
	option2: ' Changes all passwords in passwd ',
	option3: ' Add new user to the passwd file ',
	option4: ' Display passwd content to prompt',
	ans: 4,
},
{
	question: 'Which of the following is assured by the use of a hash?',
	option1: 'Authentication ',
	option2: 'Confidentiality ',
	option3: 'Availability ',
	option4: 'Integrity',
	ans: 4,
},
{
	question: 'Which results will be returned with the following Google search query? site:target.com -site:Marketing.target.com accounting',
	option1: ' Results from matches on the site marketin',
	option2: 'targe',
	option3: 'com that are in the domain targe',
	option4: 'com but do not include the word accounting',
	ans: 4,
},
{
	question: 'Email is transmitted across the Internet using the Simple Mail Transport Protocol. SMTP does not encrypt email, leaving the information in the message vulnerable to being read by an unauthorized person. SMTP can upgrade a connection between two mail servers to use TLS. Email transmitted by SMTP over TLS is encrypted. What is the name of the command used by SMTP to transmit email over TLS?',
	option1: ' OPPORTUNISTICTLS ',
	option2: ' UPGRADETLS ',
	option3: ' FORCETLS ',
	option4: ' STARTTLS',
	ans: 4,
},{
	question: 'You are a Network Security Officer. You have two machines. The first machine (192.168.0.99) has snort installed, and the second machine (192.168.0.150) has kiwi syslog installed. You perform a syn scan in your network, and you notice that kiwi syslog is not receiving the alert message from snort. You decide to run wireshark in the snort machine to check if the messages are going to the kiwi syslog machine. What Wireshark filter will show the connections from the snort machine to kiwi syslog machine?',
	option1: ' tc',
	option2: 'srcport= = 514 && i',
	option3: 'src= = 19',
	option4: '168',
	ans: 4,
},
{
	question: "You have gained physical access to a Windows 2008 R2 server, which has an accessible disc drive. When you attempt to boot the server and log in, you are unable to guess the password. In your toolkit, you have an Ubuntu 9.10 Linux LiveCD. Which Linux-based tool can change any user's password or activate disabled Windows accounts?",
	option1: ' John the Ripper ',
	option2: ' SET ',
	option3: ' CHNTPW ',
	option4: ' Cain & Abel',
	ans: 3,
},
{
	question: 'What does a firewall check to prevent particular ports and applications from getting packets into an organization?',
	option1: ' Transport layer port numbers and application layer headers ',
	option2: ' Presentation layer headers and the session layer port numbers ',
	option3: ' Network layer headers and the session layer port numbers ',
	option4: ' Application layer port numbers and the transport layer headers',
	ans: 1,
},
{
	question: 'An attacker has installed a RAT on a host. The attacker wants to ensure that when a user attempts to go to "www.MyPersonalBank.com", the user is directed to a phishing site.Which file does the attacker need to modify?',
	option1: ' Boo',
	option2: 'ini ',
	option3: ' Sudoers ',
	option4: ' Networks D',
	ans: 4,
},
{
	question: '_________ is a set of extensions to DNS that provide the origin authentication of DNS data to DNS clients (resolvers) so as to reduce the threat of DNS poisoning, spoofing, and similar types of attacks.',
	option1: ' DNSSEC ',
	option2: ' Resource records ',
	option3: ' Resource transfer ',
	option4: ' Zone transfer',
	ans: 1,
},
{
	question: 'Which of the following incident handling process phases is responsible for defining rules, collaborating human workforce, creating a back-up plan, and testing the plans for an organization?',
	option1: 'Preparation phase ',
	option2: 'Containment phase ',
	option3: 'Identification phase ',
	option4: 'Recovery phase',
	ans: 1,
},
{
	question: 'The configuration allows a wired or wireless network interface controller to pass all traffic it receives to the Central Processing Unit (CPU), rather than passing only the frames that the controller is intended to receive.Which of the following is being described?',
	option1: ' Multi-cast mode ',
	option2: ' Promiscuous mode ',
	option3: ' WEM ',
	option4: ' Port forwarding',
	ans: 2,
},
{
	question: 'A large mobile telephony and data network operator has a data center that houses network elements. These are essentially large computers running on Linux.The perimeter of the data center is secured with firewalls and IPS systems.What is the best security policy concerning this setup?',
	option1: ' Network elements must be hardened with user ids and strong password',
	option2: ' Regular security tests and audits should be performe',
	option3: ' ',
	option4: ' As long as the physical access to the network elements is restricted, there is no need for additional measures',
	ans: 1,
},
{
	question: 'PGP, SSL, and IKE are all examples of which type of cryptography?',
	option1: ' Digest ',
	option2: ' Secret Key ',
	option3: ' Public Key ',
	option4: ' Hash Algorithm',
	ans: 3,
},
{
	question: 'Peter is surfing the internet looking for information about DX Company. Which hacking process is Peter doing?',
	option1: ' Scanning ',
	option2: ' Footprinting ',
	option3: ' Enumeration ',
	option4: ' System Hacking',
	ans: 2,
},
{
	question: "A hacker is an intelligent individual with excellent computer skills and the ability to explore a computer's software and hardware without the owner's permission.Their intention can either be to simply gain knowledge or to illegally make changes.Which of the following class of hacker refers to an individual who works both offensively and defensively at various times?",
	option1: ' White Hat ',
	option2: ' Suicide Hacker ',
	option3: ' Gray Hat ',
	option4: ' Black Hat',
	ans: 3,
},
{
	question: 'During a recent security assessment, you discover the organization has one Domain Name Server (DNS) in a Demilitarized Zone (DMZ) and a second DNS server on the internal network.What is this type of DNS configuration commonly called?',
	option1: ' DynDNS ',
	option2: ' DNS Scheme ',
	option3: ' DNSSEC ',
	option4: ' Split DNS',
	ans: 4,
},
{
	question: "What kind of detection techniques is being used in antivirus software that identifies malware by collecting data from multiple protected systems and instead of analyzing files locally it's made on the provider's environment?",
	option1: ' Behavioral based ',
	option2: ' Heuristics based ',
	option3: ' Honeypot based ',
	option4: ' Cloud based',
	ans: 4,
},
{
	question: 'Which of the following tools is used to analyze the files produced by several packet-capture programs such as tcpdump, WinDump, Wireshark, and EtherPeek?',
	option1: 'tcptrace ',
	option2: ' Nessus ',
	option3: ' OpenVAS ',
	option4: ' tcptraceroute',
	ans: 1,
},
{
	question: 'What is the way to decide how a packet will move from an untrusted outside host to a protected inside that is behind a firewall, which permits the hacker to determine which ports are open and if the packets can pass through the packet-filtering of the firewall?',
	option1: ' Session hijacking ',
	option2: ' Firewalking ',
	option3: ' Man-in-the middle attack ',
	option4: ' Network sniffing',
	ans: 2,
},
{
	question: 'Which of the following is not a Bluetooth attack?',
	option1: 'Bluedriving ',
	option2: 'Bluesmacking ',
	option3: 'Bluejacking ',
	option4: 'Bluesnarfing',
	ans: 1,
},
{
	question: "While using your bank's online servicing you notice the following string in the URL bar:`http://www.MyPersonalBank.com/account?id=368940911028389&Damount=10980&Camount=21`You observe that if you modify the Damount & Camount values and submit the request, that data on the web page reflect the changes.Which type of vulnerability is present on this site?",
	option1: ' Cookie Tampering ',
	option2: ' SQL Injection ',
	option3: ' Web Parameter Tampering ',
	option4: ' XSS Reflection',
	ans: 3,
},
{
	question: 'The establishment of a TCP connection involves a negotiation called three-way handshake. What type of message does the client send to the server in order to begin this negotiation?',
	option1: ' ACK ',
	option2: ' SYN ',
	option3: ' RST ',
	option4: ' SYN-ACK',
	ans: 2,
},
{
	question: 'Which type of security feature stops vehicles from crashing through the doors of a building?',
	option1: 'Bollards ',
	option2: 'Receptionist ',
	option3: 'Mantrap ',
	option4: ' Turnstile',
	ans: 1,
},
{
	question: 'What is the purpose of a demilitarized zone on a network?',
	option1: ' To scan all traffic coming through the DMZ to the internal network ',
	option2: ' To only provide direct access to the nodes within the DMZ and protect the network behind it ',
	option3: ' To provide a place to put the honeypot ',
	option4: ' To contain the network devices you wish to protect',
	ans: 2,
},
{
	question: 'Shellshock allowed an unauthorized user to gain access to a server. It affected many Internet-facing services, which OS did it not directly affect?',
	option1: ' Linux ',
	option2: ' Unix ',
	option3: ' OS X ',
	option4: ' Windows',
	ans: 4,
},
{
	question: 'Which regulation defines security and privacy controls for Federal information systems and organizations?',
	option1: ' HIPAA ',
	option2: ' EU Safe Harbor ',
	option3: ' PCI-DSS ',
	option4: ' NIST-800-53',
	ans: 4,
},
{
	question: 'What is a `Collision attack` in cryptography?',
	option1: ' Collision attacks try to get the public key ',
	option2: ' Collision attacks try to break the hash into three parts to get the plaintext value ',
	option3: ' Collision attacks try to break the hash into two parts, with the same bytes in each part to get the private key ',
	option4: ' Collision attacks try to find two inputs producing the same hash',
	ans: 4,
},
{
	question: 'Which of the following tools can be used for passive OS fingerprinting?',
	option1: 'nmap ',
	option2: 'tcpdump ',
	option3: ' tracert ',
	option4: ' ping',
	ans: 2,
},
{
	question: 'Which of the following describes the characteristics of a Boot Sector Virus?',
	option1: ' Modifies directory table entries so that directory entries point to the virus code instead of the actual progra',
	option2: ' ',
	option3: ' Moves the MBR to another location on the RAM and copies itself to the original location of the MB',
	option4: ' C',
	ans: 3,
},
{
	question: 'Your company was hired by a small healthcare provider to perform a technical assessment on the network. What is the best approach for discovering vulnerabilities on a Windows-based computer?',
	option1: 'Use the built-in Windows Update tool ',
	option2: 'Use a scan tool like Nessus ',
	option3: ' Check MITR',
	option4: 'org for the latest list of CVE findings D',
	ans: 2,
},
{
	question: 'Which of the following is a command line packet analyzer similar to GUI-based Wireshark?',
	option1: ' nessus ',
	option2: ' tcpdump ',
	option3: ' ethereal ',
	option4: ' jack the ripper',
	ans: 2,
},
{
	question: 'DHCP snooping is a great solution to prevent rogue DHCP servers on your network. Which security feature on switchers leverages the DHCP snooping database to help prevent man-in-the-middle attacks?',
	option1: ' Spanning tree ',
	option2: ' Dynamic ARP Inspection (DAI) ',
	option3: ' Port security ',
	option4: ' Layer 2 Attack Prevention Protocol (LAPP)',
	ans: 2,
},
{
	question: 'Bob, a network administrator at BigUniversity, realized that some students are connecting their notebooks in the wired network to have Internet access. In the university campus, there are many Ethernet ports available for professors and authorized visitors but not for students.He identified this when the IDS alerted for malware activities in the network.What should Bob do to avoid this problem?',
	option1: ' Disable unused ports in the switches ',
	option2: ' Separate students in a different VLAN ',
	option3: ' Use the 80',
	option4: '1x protocol D',
	ans: 3,
},
{
	question: 'You just set up a security system in your network. In what kind of system would you find the following string of characters used as a rule within its configuration? alert tcp any any -> 192.168.100.0/24 21 (msg: ``FTP on the network!``;)',
	option1: ' A firewall IPTable ',
	option2: ' FTP Server rule ',
	option3: ' A Router IPTable ',
	option4: ' An Intrusion Detection System',
	ans: 4,
},
{
	question: 'Which of the following program infects the system boot sector and the executable files at the same time?',
	option1: ' Polymorphic virus ',
	option2: ' Stealth virus ',
	option3: ' Multipartite Virus ',
	option4: ' Macro virus',
	ans: 3,
},
{
	question: 'To determine if a software program properly handles a wide range of invalid input, a form of automated testing can be used to randomly generate invalid input in an attempt to crash the program.What term is commonly used when referring to this type of testing?',
	option1: ' Randomizing ',
	option2: ' Bounding ',
	option3: ' Mutating ',
	option4: ' Fuzzing',
	ans: 4,
},
{
	question: "An Intrusion Detection System (IDS) has alerted the network administrator to a possibly malicious sequence of packets sent to a Web server in the network's external DMZ. The packet traffic was captured by the IDS and saved to a PCAP file. What type of network tool can be used to determine if these packets are genuinely malicious or simply a false positive?",
	option1: 'Protocol analyzer ',
	option2: 'Network sniffer ',
	option3: 'Intrusion Prevention System (IPS) ',
	option4: 'Vulnerability scanner',
	ans: 1,
},
{
	question: "The Heartbleed bug was discovered in 2014 and is widely referred to under MITRE's Common Vulnerabilities and Exposures (CVE) as CVE-2014-0160. This bug affects the OpenSSL implementation of the Transport Layer Security (TLS) protocols defined in RFC6520.What type of key does this bug leave exposed to the Internet making exploitation of any compromised system very easy?",
	option1: ' Public ',
	option2: ' Private ',
	option3: ' Shared ',
	option4: ' Root',
	ans: 2,
},
{
	question: 'Why should the security analyst disable/remove unnecessary ISAPI filters?',
	option1: ' To defend against social engineering attacks ',
	option2: ' To defend against webserver attacks ',
	option3: ' To defend against jailbreaking ',
	option4: ' To defend against wireless attacks',
	ans: 2,
},
{
	question: 'Which of the following is a component of a risk assessment?',
	option1: ' Administrative safeguards ',
	option2: ' Physical security ',
	option3: ' DMZ ',
	option4: ' Logical interface',
	ans: 1,
},
{
	question: "CompanyXYZ has asked you to assess the security of their perimeter email gateway. From your office in New York, you craft a specially formatted email message and send it across the Internet to an employee of CompanyXYZ. The employee of CompanyXYZ is aware of your test. Your email message looks like this:From: [email&#160;protected] -To: [email&#160;protected]Subject: Test message -Date: 4/3/2017 14:37 -The employee of CompanyXYZ receives your email message.This proves that CompanyXYZ's email gateway doesn't prevent what?",
	option1: 'Email Masquerading ',
	option2: 'Email Harvesting ',
	option3: ' Email Phishing ',
	option4: 'Email Spoofing',
	ans: 4,
},
{
	question: 'Bob, a system administrator at TPNQM SA, concluded one day that a DMZ is not needed if he properly configures the firewall to allow access just to servers/ports, which can have direct internet access, and block the access to workstations.Bob also concluded that DMZ makes sense just when a stateful firewall is available, which is not the case of TPNQM SA.In this context, what can you say?',
	option1: ' Bob can be right since DMZ does not make sense when combined with stateless firewalls ',
	option2: ' Bob is partially righ',
	option3: ' He does not need to separate networks if he can create rules by destination IPs, one by one ',
	option4: ' Bob is totally wrong',
	ans: 3,
},
{
	question: 'Which of the following commands checks for valid users on an SMTP server?',
	option1: ' RCPT ',
	option2: ' CHK ',
	option3: ' VRFY ',
	option4: ' EXPN',
	ans: 3,
},
{
	question: 'Wilson, a professional hacker, targets an organization for financial benefit and plans to compromise its systems by sending malicious emails. For this purpose, he uses a tool to track the emails of the target and extracts information such as sender identities, mail servers, sender IP addresses, and sender locations from different public sources. He also checks if an email address was leaked using the haveibeenpwned.com API.Which of the following tools is used by Wilson in the above scenario?',
	option1: 'Factiva ',
	option2: 'ZoomInfo ',
	option3: 'Netcraft ',
	option4: 'Infoga',
	ans: 4,
},
{
	question: 'Bob, an attacker, has managed to access a target IoT device. He employed an online tool to gather information related to the model of the IoT device and the certifications granted to it.Which of the following tools did Bob employ to gather the above information?',
	option1: ' FCC ID search ',
	option2: ' Google image search ',
	option3: ' searc',
	option4: 'com D',
	ans: 1,
},
{
	question: "A penetration tester is performing the footprinting process and is reviewing publicly available information about an organization by using the Google search engine.Which of the following advanced operators would allow the pen tester to restrict the search to the organization's web domain?",
	option1: ' [allinurl:] ',
	option2: ' [location:] ',
	option3: ' [site:] ',
	option4: ' [link:]',
	ans: 3,
},
{
	question: 'Annie, a cloud security engineer, uses the Docker architecture to employ a client/server model in the application she is working on. She utilizes a component that can process API requests and handle various Docker objects, such as containers, volumes, images, and networks.What is the component of the Docker architecture used by Annie in the above scenario?',
	option1: ' Docker objects ',
	option2: ' Docker daemon ',
	option3: ' Docker client ',
	option4: ' Docker registries',
	ans: 2,
},
{
	question: "You are a penetration tester working to test the user awareness of the employees of the client XYZ. You harvested two employees' emails from some public sources and are creating a client-side backdoor to send it to the employees via email.Which stage of the cyber kill chain are you at?",
	option1: ' Reconnaissance ',
	option2: ' Weaponization ',
	option3: ' Command and control ',
	option4: ' Exploitation',
	ans: 4,
},
{
	question: "Sam is working as a system administrator in an organization. He captured the principal characteristics of a vulnerability and produced a numerical score to reflect its severity using CVSS v3.0 to properly assess and prioritize the organization's vulnerability management processes. The base score that Sam obtained after performing CVSS rating was 4.0.What is the CVSS severity level of the vulnerability discovered by Sam in the above scenario?",
	option1: ' Critical ',
	option2: ' Medium ',
	option3: ' High ',
	option4: ' Low',
	ans: 2,
},
{
	question: 'The network users are complaining because their systems are slowing down. Further, every time they attempt to go to a website, they receive a series of pop-ups with advertisements. What type of malware have the systems been infected with?',
	option1: ' Trojan ',
	option2: ' Spyware ',
	option3: ' Virus ',
	option4: ' Adware',
	ans: 4,
},
{
	question: "SQL injection (SQLi) attacks attempt to inject SQL syntax into web requests, which may bypass authentication and allow attackers to access and/or modify data attached to a web application.Which of the following SQLi types leverages a database server's ability to make DNS requests to pass data to an attacker?",
	option1: ' In-band SQLi ',
	option2: ' Union-based SQLi ',
	option3: ' Out-of-band SQLi ',
	option4: ' Time-based blind SQLi',
	ans: 3,
},
{
	question: 'Which type of virus can change its own code and then cipher itself multiple times as it replicates?',
	option1: 'Stealth virus ',
	option2: ' Tunneling virus ',
	option3: ' Cavity virus ',
	option4: 'Encryption virus',
	ans: 1,
},
{
	question: 'What is the port to block first in case you are suspicious that an IoT device has been compromised?',
	option1: ' 22 ',
	option2: ' 48101 ',
	option3: ' 80 ',
	option4: ' 443',
	ans: 2,
},
{
	question: 'Techno Security Inc. recently hired John as a penetration tester. He was tasked with identifying open ports in the target network and determining whether the ports are online and any firewall rule sets are encountered.John decided to perform a TCP SYN ping scan on the target network.Which of the following Nmap commands must John use to perform the TCP SYN ping scan?',
	option1: ' nmap -sn -PO &lt; target IP address > ',
	option2: ' nmap -sn -PS &lt; target IP address > ',
	option3: ' nmap -sn -PA &lt; target IP address > ',
	option4: ' nmap -sn -PP &lt; target IP address >',
	ans: 2,
},
{
    question: " Which device is required for the Internet connection?",
    option1: "Modem",
    option2: "Router",
    option3: "LAN Cable",
    option4: "Pen Drive",
    ans: 1,
  },
  {
    question: "Which continent has the highest number of countries?",
    option1: "Asia",
    option2: "Europe",
    option3: "North America",
    option4: "Africa",
    ans: 4,
  },
  {
    question: "Junk e-mail is also called?",
    option1: "Spam",
    option2: "Fake",
    option3: "Archived",
    option4: "Bin",
    ans: 1,
  },
  {
    question: "A computer cannot BOOT if it does not have the?",
    option1: "Application Software",
    option2: "Internet",
    option3: "Operating System",
    option4: "Mouse",
    ans: 3,
  },
  {
    question: "First page of Website is termed as?",
    option1: "Index Page",
    option2: "Homepage",
    option3: "Sitemap",
    option4: "Pen Drive",
    ans: 2,
  },
